### ISSUE TITLE
cinnamon install help?

### ISSUE THREAD

**Issue by gilbrotheraway** [QuantiusBenignus/blurt#8]
how would you go about installing it on cinmamon?

**Comment by QuantiusBenignus** [comment]
I would suggest using [BlahST](https://github.com/QuantiusBenignus/BlahST), which has superseded blurt because:
1. It will work in any desktop environment that can set global keyboard hotkeys.
2. Does everything that blurt does with lower GPU overhead (no GUI and no extra JS code in the shell).
3. Adds extra features that make it more powerful and easy to use, once properly installed, for example autopaste and AI interaction.
4. The update cycle does not need to constantly chase Gnome shell version updates. 

In light of the above, BlahST will have higher priority for maintenance in the future. Check it out and see if it works for you.

For BlahST, in general, one needs to clone the repo, run the install script `install-wsi`, then run one of the scripts ( wsi is a good start, wsiml adds multilingual input, wsiAI adds local LLM interaction) with the desired command line parameters (check the Config section in each of the run scripts) from the terminal to make sure they work. 
After that set up the global hotkeys as described in the README and enjoy speech input in any window or local AI interaction.
